# Bedrock tick - 80 calls + events
execute as @a at @s if score @s novahorror.timer matches 0 run function func_000
execute as @a at @s if score @s novahorror.timer matches 1 run function func_001
execute as @a at @s if score @s novahorror.timer matches 2 run function func_002
execute as @a at @s if score @s novahorror.timer matches 3 run function func_003
execute as @a at @s if score @s novahorror.timer matches 4 run function func_004
execute as @a at @s if score @s novahorror.timer matches 5 run function func_005
execute as @a at @s if score @s novahorror.timer matches 6 run function func_006
execute as @a at @s if score @s novahorror.timer matches 7 run function func_007
execute as @a at @s if score @s novahorror.timer matches 8 run function func_008
execute as @a at @s if score @s novahorror.timer matches 9 run function func_009
execute as @a at @s if score @s novahorror.timer matches 10 run function func_010
execute as @a at @s if score @s novahorror.timer matches 11 run function func_011
execute as @a at @s if score @s novahorror.timer matches 12 run function func_012
execute as @a at @s if score @s novahorror.timer matches 13 run function func_013
execute as @a at @s if score @s novahorror.timer matches 14 run function func_014
execute as @a at @s if score @s novahorror.timer matches 15 run function func_015
execute as @a at @s if score @s novahorror.timer matches 16 run function func_016
execute as @a at @s if score @s novahorror.timer matches 17 run function func_017
execute as @a at @s if score @s novahorror.timer matches 18 run function func_018
execute as @a at @s if score @s novahorror.timer matches 19 run function func_019
execute as @a at @s if score @s novahorror.timer matches 20 run function func_020
execute as @a at @s if score @s novahorror.timer matches 21 run function func_021
execute as @a at @s if score @s novahorror.timer matches 22 run function func_022
execute as @a at @s if score @s novahorror.timer matches 23 run function func_023
execute as @a at @s if score @s novahorror.timer matches 24 run function func_024
execute as @a at @s if score @s novahorror.timer matches 25 run function func_025
execute as @a at @s if score @s novahorror.timer matches 26 run function func_026
execute as @a at @s if score @s novahorror.timer matches 27 run function func_027
execute as @a at @s if score @s novahorror.timer matches 28 run function func_028
execute as @a at @s if score @s novahorror.timer matches 29 run function func_029
execute as @a at @s if score @s novahorror.timer matches 30 run function func_030
execute as @a at @s if score @s novahorror.timer matches 31 run function func_031
execute as @a at @s if score @s novahorror.timer matches 32 run function func_032
execute as @a at @s if score @s novahorror.timer matches 33 run function func_033
execute as @a at @s if score @s novahorror.timer matches 34 run function func_034
execute as @a at @s if score @s novahorror.timer matches 35 run function func_035
execute as @a at @s if score @s novahorror.timer matches 36 run function func_036
execute as @a at @s if score @s novahorror.timer matches 37 run function func_037
execute as @a at @s if score @s novahorror.timer matches 38 run function func_038
execute as @a at @s if score @s novahorror.timer matches 39 run function func_039
execute as @a at @s if score @s novahorror.timer matches 40 run function func_040
execute as @a at @s if score @s novahorror.timer matches 41 run function func_041
execute as @a at @s if score @s novahorror.timer matches 42 run function func_042
execute as @a at @s if score @s novahorror.timer matches 43 run function func_043
execute as @a at @s if score @s novahorror.timer matches 44 run function func_044
execute as @a at @s if score @s novahorror.timer matches 45 run function func_045
execute as @a at @s if score @s novahorror.timer matches 46 run function func_046
execute as @a at @s if score @s novahorror.timer matches 47 run function func_047
execute as @a at @s if score @s novahorror.timer matches 48 run function func_048
execute as @a at @s if score @s novahorror.timer matches 49 run function func_049
execute as @a at @s if score @s novahorror.timer matches 50 run function func_050
execute as @a at @s if score @s novahorror.timer matches 51 run function func_051
execute as @a at @s if score @s novahorror.timer matches 52 run function func_052
execute as @a at @s if score @s novahorror.timer matches 53 run function func_053
execute as @a at @s if score @s novahorror.timer matches 54 run function func_054
execute as @a at @s if score @s novahorror.timer matches 55 run function func_055
execute as @a at @s if score @s novahorror.timer matches 56 run function func_056
execute as @a at @s if score @s novahorror.timer matches 57 run function func_057
execute as @a at @s if score @s novahorror.timer matches 58 run function func_058
execute as @a at @s if score @s novahorror.timer matches 59 run function func_059
execute as @a at @s if score @s novahorror.timer matches 60 run function func_060
execute as @a at @s if score @s novahorror.timer matches 61 run function func_061
execute as @a at @s if score @s novahorror.timer matches 62 run function func_062
execute as @a at @s if score @s novahorror.timer matches 63 run function func_063
execute as @a at @s if score @s novahorror.timer matches 64 run function func_064
execute as @a at @s if score @s novahorror.timer matches 65 run function func_065
execute as @a at @s if score @s novahorror.timer matches 66 run function func_066
execute as @a at @s if score @s novahorror.timer matches 67 run function func_067
execute as @a at @s if score @s novahorror.timer matches 68 run function func_068
execute as @a at @s if score @s novahorror.timer matches 69 run function func_069
execute as @a at @s if score @s novahorror.timer matches 70 run function func_070
execute as @a at @s if score @s novahorror.timer matches 71 run function func_071
execute as @a at @s if score @s novahorror.timer matches 72 run function func_072
execute as @a at @s if score @s novahorror.timer matches 73 run function func_073
execute as @a at @s if score @s novahorror.timer matches 74 run function func_074
execute as @a at @s if score @s novahorror.timer matches 75 run function func_075
execute as @a at @s if score @s novahorror.timer matches 76 run function func_076
execute as @a at @s if score @s novahorror.timer matches 77 run function func_077
execute as @a at @s if score @s novahorror.timer matches 78 run function func_078
execute as @a at @s if score @s novahorror.timer matches 79 run function func_079
scoreboard players add @a novahorror.timer 1
execute if score @a novahorror.timer matches 80.. run scoreboard players set @a novahorror.timer 0
